### ISSUE TITLE
Better auto-tracking indication

### ISSUE THREAD

**Issue by fenhl** [fenhl/oottracker#5]
- [x] Show “(auto-tracker connected)” in the title bar (74413fcdc7bc4da8f5ed698713151eafe561d678)
- [x] Use a better message for the `ClientConnected` notification and auto-close it (but not the `ClientDisconnected` one) after 10 seconds (74413fcdc7bc4da8f5ed698713151eafe561d678)
- [x] Replace triforce pieces cell with big poe count if triforce hunt is off
- [ ] Adjust magic meter and mirror shield colors once obtained
